[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$/H/PuTcmBICQUoqR0tq7tw$ao7mH7PnzK3/4.Wi3n1/8RY3kBzElUlAM7HNlR1D8/MarCN6JBOLwaK/zft17Zhb4UQvuhm8XRNTjHh7Qtcx1g
db_host = db19
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
list_db = True
log_level = info

